version: '3'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - client
      - cat-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  client:
    image: client
    container_name: client
    build:
      context: ./client
    depends_on:
      - cat-service
    ports:
      - 8080:80
    restart: on-failure

  cat-service:
    image: cat-service
    container_name: cat-service
    build:
      context: ./cat_service
    ports:
      - 5001:5001
    restart: on-failure